# Generated by Django 5.2 on 2025-07-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notification__notific_8b8c8c_idx",
        ),
        migrations.RemoveIndex(
            model_name="usernotificationpreference",
            name="user_notific_user_id_8b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_218e2a_idx",
            old_name="notifications_recipie_8b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_created_e4c995_idx",
            old_name="notifications_created_8b8c8c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_schedul_3d00b6_idx",
            old_name="notifications_schedul_8b8c8c_idx",
        ),
    ]
