"""Add DOT and Park tables

Revision ID: 2b514c5c352d
Revises: b0534cfbd85a
Create Date: 2025-09-25 00:07:23.684521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b514c5c352d'
down_revision: Union[str, None] = 'b0534cfbd85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_dots_id'), 'dots', ['id'], unique=False)
    op.create_index(op.f('ix_dots_name'), 'dots', ['name'], unique=True)
    op.create_table('parks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('extraction_date', sa.Date(), nullable=True),
                    sa.Column('dot_id', sa.Integer(), nullable=True),
                    sa.Column('actel_code', sa.String(
                        length=100), nullable=True),
                    sa.Column('customer_l1_code', sa.String(
                        length=100), nullable=True),
                    sa.Column('customer_l1_description',
                              sa.String(length=255), nullable=True),
                    sa.Column('customer_l2_code', sa.String(
                        length=100), nullable=True),
                    sa.Column('customer_l2_description',
                              sa.String(length=255), nullable=True),
                    sa.Column('customer_l3_code', sa.String(
                        length=100), nullable=True),
                    sa.Column('customer_l3_description',
                              sa.String(length=255), nullable=True),
                    sa.Column('telecom_type', sa.String(
                        length=100), nullable=True),
                    sa.Column('offer_type', sa.String(
                        length=100), nullable=True),
                    sa.Column('offer_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('rental_fees', sa.Numeric(
                        precision=10, scale=2), nullable=True),
                    sa.Column('customer_code', sa.String(
                        length=100), nullable=True),
                    sa.Column('service_number', sa.String(
                        length=100), nullable=True),
                    sa.Column('related_service_number',
                              sa.String(length=100), nullable=True),
                    sa.Column('username', sa.String(
                        length=255), nullable=True),
                    sa.Column('subscriber_status', sa.String(
                        length=100), nullable=True),
                    sa.Column('status_date', sa.Date(), nullable=True),
                    sa.Column('creation_date', sa.Date(), nullable=True),
                    sa.Column('active_date', sa.Date(), nullable=True),
                    sa.Column('csr_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('department_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('state', sa.String(length=100), nullable=True),
                    sa.Column('area', sa.String(length=100), nullable=True),
                    sa.Column('town', sa.String(length=100), nullable=True),
                    sa.Column('grid', sa.String(length=100), nullable=True),
                    sa.Column('street', sa.String(length=255), nullable=True),
                    sa.Column('street_number', sa.String(
                        length=50), nullable=True),
                    sa.Column('building_no', sa.String(
                        length=50), nullable=True),
                    sa.Column('unit', sa.String(length=50), nullable=True),
                    sa.Column('floor', sa.String(length=50), nullable=True),
                    sa.Column('house_no', sa.String(length=50), nullable=True),
                    sa.Column('additional_address_info',
                              sa.Text(), nullable=True),
                    sa.Column('customer_full_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('province', sa.String(
                        length=100), nullable=True),
                    sa.Column('district', sa.String(
                        length=100), nullable=True),
                    sa.Column('city', sa.String(length=100), nullable=True),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=True),
                    sa.Column('expiry_date', sa.Date(), nullable=True),
                    sa.Column('iccid', sa.String(length=100), nullable=True),
                    sa.Column('imsi', sa.String(length=100), nullable=True),
                    sa.Column('contact_number', sa.String(
                        length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['dot_id'], ['dots.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_parks_actel_code'), 'parks',
                    ['actel_code'], unique=False)
    op.create_index(op.f('ix_parks_area'), 'parks', ['area'], unique=False)
    op.create_index(op.f('ix_parks_city'), 'parks', ['city'], unique=False)
    op.create_index(op.f('ix_parks_customer_code'), 'parks',
                    ['customer_code'], unique=False)
    op.create_index(op.f('ix_parks_customer_full_name'),
                    'parks', ['customer_full_name'], unique=False)
    op.create_index(op.f('ix_parks_customer_l1_code'), 'parks',
                    ['customer_l1_code'], unique=False)
    op.create_index(op.f('ix_parks_customer_l2_code'), 'parks',
                    ['customer_l2_code'], unique=False)
    op.create_index(op.f('ix_parks_customer_l3_code'), 'parks',
                    ['customer_l3_code'], unique=False)
    op.create_index(op.f('ix_parks_district'), 'parks',
                    ['district'], unique=False)
    op.create_index(op.f('ix_parks_dot_id'), 'parks', ['dot_id'], unique=False)
    op.create_index(op.f('ix_parks_extraction_date'), 'parks',
                    ['extraction_date'], unique=False)
    op.create_index(op.f('ix_parks_iccid'), 'parks', ['iccid'], unique=False)
    op.create_index(op.f('ix_parks_id'), 'parks', ['id'], unique=False)
    op.create_index(op.f('ix_parks_imsi'), 'parks', ['imsi'], unique=False)
    op.create_index(op.f('ix_parks_offer_type'), 'parks',
                    ['offer_type'], unique=False)
    op.create_index(op.f('ix_parks_province'), 'parks',
                    ['province'], unique=False)
    op.create_index(op.f('ix_parks_service_number'), 'parks',
                    ['service_number'], unique=False)
    op.create_index(op.f('ix_parks_state'), 'parks', ['state'], unique=False)
    op.create_index(op.f('ix_parks_subscriber_status'),
                    'parks', ['subscriber_status'], unique=False)
    op.create_index(op.f('ix_parks_telecom_type'), 'parks',
                    ['telecom_type'], unique=False)
    op.create_index(op.f('ix_parks_town'), 'parks', ['town'], unique=False)
    # Foreign key constraints are not supported in SQLite for existing tables
    # They will be handled at the application level
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key constraints are not supported in SQLite for existing tables
    op.drop_index(op.f('ix_parks_town'), table_name='parks')
    op.drop_index(op.f('ix_parks_telecom_type'), table_name='parks')
    op.drop_index(op.f('ix_parks_subscriber_status'), table_name='parks')
    op.drop_index(op.f('ix_parks_state'), table_name='parks')
    op.drop_index(op.f('ix_parks_service_number'), table_name='parks')
    op.drop_index(op.f('ix_parks_province'), table_name='parks')
    op.drop_index(op.f('ix_parks_offer_type'), table_name='parks')
    op.drop_index(op.f('ix_parks_imsi'), table_name='parks')
    op.drop_index(op.f('ix_parks_id'), table_name='parks')
    op.drop_index(op.f('ix_parks_iccid'), table_name='parks')
    op.drop_index(op.f('ix_parks_extraction_date'), table_name='parks')
    op.drop_index(op.f('ix_parks_dot_id'), table_name='parks')
    op.drop_index(op.f('ix_parks_district'), table_name='parks')
    op.drop_index(op.f('ix_parks_customer_l3_code'), table_name='parks')
    op.drop_index(op.f('ix_parks_customer_l2_code'), table_name='parks')
    op.drop_index(op.f('ix_parks_customer_l1_code'), table_name='parks')
    op.drop_index(op.f('ix_parks_customer_full_name'), table_name='parks')
    op.drop_index(op.f('ix_parks_customer_code'), table_name='parks')
    op.drop_index(op.f('ix_parks_city'), table_name='parks')
    op.drop_index(op.f('ix_parks_area'), table_name='parks')
    op.drop_index(op.f('ix_parks_actel_code'), table_name='parks')
    op.drop_table('parks')
    op.drop_index(op.f('ix_dots_name'), table_name='dots')
    op.drop_index(op.f('ix_dots_id'), table_name='dots')
    op.drop_table('dots')
    # ### end Alembic commands ###
