"""increase_park_field_lengths

Revision ID: 32a559dc88a5
Revises: 29bac152752d
Create Date: 2025-09-25 02:35:56.751550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a559dc88a5'
down_revision: Union[str, None] = '29bac152752d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_data_row_number', table_name='file_data_rows')
    op.drop_index('idx_file_data_row_table_id', table_name='file_data_rows')
    op.drop_index('idx_file_data_row_table_row', table_name='file_data_rows')
    op.drop_index('ix_file_data_rows_id', table_name='file_data_rows')
    op.drop_table('file_data_rows')
    op.drop_index('idx_file_data_column_name', table_name='file_data_columns')
    op.drop_index('idx_file_data_column_table_id', table_name='file_data_columns')
    op.drop_index('idx_file_data_column_table_name', table_name='file_data_columns')
    op.drop_index('ix_file_data_columns_id', table_name='file_data_columns')
    op.drop_table('file_data_columns')
    op.drop_index('idx_file_data_table_status', table_name='file_data_tables')
    op.drop_index('idx_file_data_table_upload_id', table_name='file_data_tables')
    op.drop_index('ix_file_data_tables_id', table_name='file_data_tables')
    op.drop_table('file_data_tables')
    op.alter_column('parks', 'state',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'area',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'town',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'grid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'street',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('parks', 'street_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'building_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'floor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'house_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'customer_full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('parks', 'province',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'district',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('parks', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'contact_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parks', 'contact_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'postal_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('parks', 'city',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'district',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'province',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'customer_full_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('parks', 'house_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'floor',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'unit',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'building_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'street_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('parks', 'street',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('parks', 'grid',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'town',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'area',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parks', 'state',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('file_data_tables',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('file_data_tables_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_columns', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_definitions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_uploads.id'], name='file_data_tables_file_upload_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_data_tables_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_file_data_tables_id', 'file_data_tables', ['id'], unique=False)
    op.create_index('idx_file_data_table_upload_id', 'file_data_tables', ['file_upload_id'], unique=False)
    op.create_index('idx_file_data_table_status', 'file_data_tables', ['processing_status'], unique=False)
    op.create_table('file_data_columns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('column_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('null_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['file_data_tables.id'], name='file_data_columns_data_table_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_data_columns_pkey')
    )
    op.create_index('ix_file_data_columns_id', 'file_data_columns', ['id'], unique=False)
    op.create_index('idx_file_data_column_table_name', 'file_data_columns', ['data_table_id', 'column_name'], unique=False)
    op.create_index('idx_file_data_column_table_id', 'file_data_columns', ['data_table_id'], unique=False)
    op.create_index('idx_file_data_column_name', 'file_data_columns', ['column_name'], unique=False)
    op.create_table('file_data_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_table_id'], ['file_data_tables.id'], name='file_data_rows_data_table_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_data_rows_pkey')
    )
    op.create_index('ix_file_data_rows_id', 'file_data_rows', ['id'], unique=False)
    op.create_index('idx_file_data_row_table_row', 'file_data_rows', ['data_table_id', 'row_number'], unique=False)
    op.create_index('idx_file_data_row_table_id', 'file_data_rows', ['data_table_id'], unique=False)
    op.create_index('idx_file_data_row_number', 'file_data_rows', ['row_number'], unique=False)
    # ### end Alembic commands ###
