"""Initial migration

Revision ID: 5c8e2236f82f
Revises: b0534cfbd85a
Create Date: 2025-07-28 20:28:41.897779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8e2236f82f'
down_revision: Union[str, None] = 'b0534cfbd85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    # ### end Alembic commands ###
