"""Add secure messaging features, audit logs, and WebSocket support

Revision ID: bccabf43e697
Revises: fd3d43215e25
Create Date: 2025-09-28 04:45:55.254463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccabf43e697'
down_revision: Union[str, None] = 'fd3d43215e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_read_receipts_id'), 'message_read_receipts', ['id'], unique=False)
    op.add_column('messages', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('encryption_version', sa.String(length=10), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('thread_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'thread_id')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'encryption_version')
    op.drop_column('messages', 'content_hash')
    op.drop_index(op.f('ix_message_read_receipts_id'), table_name='message_read_receipts')
    op.drop_table('message_read_receipts')
    # ### end Alembic commands ###
