"""add_file_upload_id_to_parks

Revision ID: e80792660d82
Revises: 32a559dc88a5
Create Date: 2025-09-25 03:05:40.828873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80792660d82'
down_revision: Union[str, None] = '32a559dc88a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parks', sa.Column('file_upload_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parks_file_upload_id'), 'parks', ['file_upload_id'], unique=False)
    op.create_foreign_key(None, 'parks', 'file_uploads', ['file_upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parks', type_='foreignkey')
    op.drop_index(op.f('ix_parks_file_upload_id'), table_name='parks')
    op.drop_column('parks', 'file_upload_id')
    # ### end Alembic commands ###
