"""Add DOT relationship to User model

Revision ID: fd3d43215e25
Revises: e80792660d82
Create Date: 2025-09-25 04:02:28.321795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3d43215e25'
down_revision: Union[str, None] = 'e80792660d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_dot_id'), 'users', ['dot_id'], unique=False)
    op.create_foreign_key(None, 'users', 'dots', ['dot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_dot_id'), table_name='users')
    op.drop_column('users', 'dot_id')
    # ### end Alembic commands ###
